### ISSUE TITLE
Error decompiling .apk

### ISSUE THREAD

**Issue by 7-75** [ohaz/antiproguard#2]
I have no clue what this is related to, I run the command 
python antiproguard.py -d '/home/user/Downloads/file.apk'  
EDIT: It was run in a virtualenv

```
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec: [/tmp/brut_util_Jar_4325163802591262173.tmp, p, --forced-package-id, 127, --min-sdk-version, 20, --target-sdk-version, 29, --version-code, 1, --version-name, 1.0, -F, /tmp/APKTOOL2417516611649045186.tmp, -0, arsc, -0, META-INF/com.google.dagger_dagger.version, -0, META-INF/services/javax.xml.bind.JAXBContext, -0, arsc, -I, /home/tizianods/.local/share/apktool/framework/1.apk, -S, /home/tizianods/venv/venv2/antiproguard/decompiled/pbo/res, -M, /home/tizianods/venv/venv2/antiproguard/decompiled/pbo/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:473)
	at brut.androlib.Androlib.buildResources(Androlib.java:407)
	at brut.androlib.Androlib.build(Androlib.java:306)
	at brut.androlib.Androlib.build(Androlib.java:263)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec: [/tmp/brut_util_Jar_4325163802591262173.tmp, p, --forced-package-id, 127, --min-sdk-version, 20, --target-sdk-version, 29, --version-code, 1, --version-name, 1.0, -F, /tmp/APKTOOL2417516611649045186.tmp, -0, arsc, -0, META-INF/com.google.dagger_dagger.version, -0, META-INF/services/javax.xml.bind.JAXBContext, -0, arsc, -I, /home/tizianods/.local/share/apktool/framework/1.apk, -S, /home/tizianods/venv/venv2/antiproguard/decompiled/pbo/res, -M, /home/tizianods/venv/venv2/antiproguard/decompiled/pbo/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:439)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:459)
	... 5 more
Caused by: brut.common.BrutException: could not exec: [/tmp/brut_util_Jar_4325163802591262173.tmp, p, --forced-package-id, 127, --min-sdk-version, 20, --target-sdk-version, 29, --version-code, 1, --version-name, 1.0, -F, /tmp/APKTOOL2417516611649045186.tmp, -0, arsc, -0, META-INF/com.google.dagger_dagger.version, -0, META-INF/services/javax.xml.bind.JAXBContext, -0, arsc, -I, /home/tizianods/.local/share/apktool/framework/1.apk, -S, /home/tizianods/venv/venv2/antiproguard/decompiled/pbo/res, -M, /home/tizianods/venv/venv2/antiproguard/decompiled/pbo/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:97)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:433)
	... 6 more
Caused by: java.io.IOException: Cannot run program "/tmp/brut_util_Jar_4325163802591262173.tmp": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
	at brut.util.OS.exec(OS.java:90)
	... 7 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:187)
	at java.lang.ProcessImpl.start(ProcessImpl.java:130)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
	... 8 more
>> Removing output folder


```

**Comment by ohaz** [comment]
Phew, sorry, I have no clue what could cause this. brut.androidlib seems to be part of APKTool, so I guess either the current version of APKTool is not compatible with my scripts anymore, or they have a bug.

**Comment by lukin-k** [comment]
try use aapt2
